[project]
name = "hprof"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numba>=0.60.0",
    "psutil>=6.0.0",
    "pudb>=2024.1.2",
    "pytest>=8.3.3",
    "ruff>=0.6.9",
]
